### PR TITLE
Add an option <extraArgs> to let user pass custom parameters to protoc command

### LINKED ISSUE #61: Allow Providing Parameters to Built in Plugin
I would like to be able to provide a command line parameter to the build-in csharp plugin (`--csharp_opt=base_namespace=Com`). Allow `<plugInParameter>` tag to be able to pass an argument to protoc.

Example:
bfmyr4 @bfmyr4 May 28 09:31
I must be missing something. I just want to use the built in compile-csharp goal. Something like this doesn't seem to work. Example:
```xml
<plugin>
<groupId>org.xolstice.maven.plugins</groupId>
<artifactId>protobuf-maven-plugin</artifactId>
<version>0.6.1</version>
<executions>
<execution>
<id>java</id>
<goals>
<goal>compile</goal>
<goal>test-compile</goal>
</goals>
</execution>
<execution>
<id>csharp</id>
<goals>
<goal>compile-csharp</goal>
</goals>
<configuration>
<pluginParameter>--csharp_opt=base_namespace=Com</pluginParameter>
<protocArtifact>com.google.protobuf:protoc:3.7.1:exe:${os.detected.classifier}</protocArtifact>
<attachProtoSources>false</attachProtoSources>
<useArgumentFile>true</useArgumentFile>
</configuration>
</execution>
</executions>
<configuration>
<protocArtifact>com.google.protobuf:protoc:3.7.1:exe:${os.detected.classifier}</protocArtifact>
<attachProtoSources>false</attachProtoSources>
<useArgumentFile>true</useArgumentFile>
</configuration>
</plugin>
```

### PR DESCRIPTION
**Pull request by sebastienvermeille**
# Add an option <extraArgs> to let user pass custom parameters to protoc command

That way we can use all available protoc plugins with their custom options

**Applicable Issues**
Fixes #61 #77

**Description**
Add configuration <extraArgs> (optional) which is appended in the the `protoc` command invoked by the maven plugin.
This way we can easily address the issue of wanting to pass some specific parameters to protoc when running the plugin.

In my case I needed to pass some specific plugin arguments:

```
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>protodoc</id>
            <goals>
              <goal>compile-custom</goal>
            </goals>
            <configuration>
              <pluginId>protoc-gen-doc</pluginId>
              <pluginExecutable>${project.build.directory}/protoc-plugins/protoc-gen-doc-1.4.1.linux-amd64.go1.15.2/protoc-gen-doc</pluginExecutable>
              <outputDirectory>${project.build.directory}/doc</outputDirectory>
              <extraArgs>--protoc-gen-doc_opt=markdown,README.md</extraArgs>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.4.0:exe:${os.detected.classifier}</protocArtifact>
        </configuration>
      </plugin>
```

This way I can pass `--protoc-gen-doc_opt=markdown,README.md` and everything works fine.

Happy to be able to contribute to a such great project! I stay available for more assistance on it and to discuss it of course thank you :+1:

### CODE REVIEW

**Comment by bfmyr4** [comment]
Any chance on getting this into a new release?

**Comment by annyugen** [comment]
Also curious on this update. Really love to have this so I can configure NullAway to not scan generated classes

**Comment by sebastienvermeille** [comment]
Hi, okay it seems that this project is no longer maintained, I will fork it and host it on maven myself. @nguyenAn1201 @bfmyr4 sorry for the delay, I will ping you when it's ready if you still need it :)

**Comment by seime** [comment]
Hi @sebastienvermeille , are you intending to become the new maintainer if this project, and by that review and merge PRs? If so I applaud you, and we're happy to switch to your releases when available.

Cheers

**Comment by sebastienvermeille** [comment]
@seime Yes it's on my plans but unfortunately lack a bit of time.

If you need this PR code in your projects I hosted it already on maven central:

```
<dependency>
  <groupId>dev.cookiecode</groupId>
  <artifactId>protobuf-maven-plugin</artifactId>
  <version>0.7.1</version>
  <type>maven-plugin</type>
</dependency>
```

**Comment by seime** [comment]
> @seime Yes it's on my plans but unfortunately lack a bit of time.
> 
> If you need this PR code in your projects I hosted it already on maven central:

Thanks @sebastienvermeille , we have switched to your fork. Looking forward to next releases!

**Comment by sergei-ivanov** [comment]
@sebastienvermeille would you like to officially take over the project as a principal committer?

**Comment by sebastienvermeille** [comment]
@sergei-ivanov yes would be great as it's a central lib for many other projects I would like to do that for sure.
Let's have a talk

**Pull request closed without merging**
